<a href="https://colab.research.google.com/github/jafetimbre/optimus/blob/master/src/lab_2.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Generatoare de liste

In [ ]:
L = [x + y for x in 'abc' for y in 'lmnpq']
print(f'Primul generator de lista: {L}')

L = [x + y for (x, y) in zip('abc', 'lmnpq')]
print(f'Al doilea generator de lista: {L}')

Primul generator de lista: ['al', 'am', 'an', 'ap', 'aq', 'bl', 'bm', 'bn', 'bp', 'bq', 'cl', 'cm', 'cn', 'cp', 'cq']
Al doilea generator de lista: ['al', 'bm', 'cn']


In [ ]:
M = [ [1,2,3], [4,5,6], [7,8,9]]
m = [ [col + 10 for col in row] for row in M]

print(f'Prima expresie: {M}')
print(f'A doua expresie: {m}')

Prima expresie: [[1, 2, 3], [4, 5, 6], [7, 8, 9]]
A doua expresie: [[11, 12, 13], [14, 15, 16], [17, 18, 19]]


In [ ]:
R = range(5)
print(type(R))
L1, L2 = iter(R), iter(R)
print([next(L1), next(L1), next(L1)])
print([next(L2), next(L2)])

<class 'range'>
[0, 1, 2]
[0, 1]


In [ ]:
import timeit

expr = '[abs(x) for x in range(1000)]\nlist(abs(x) for x in range(1000))'

print(timeit.timeit(expr, number = 10000))

print(timeit.timeit('[abs(x) for x in range(1000)]', number = 10000))
print(timeit.timeit('list(abs(x) for x in range(1000))', number = 10000))
print(timeit.timeit('map(abs,range(1000))', number = 10000))
print(timeit.timeit('list(map(abs,range(1000)))', number = 10000))

2.6679140999999618
0.9788963000000876
1.2854178000000047
0.0040117999999438325
0.4548700000000281


# NumPy

In [ ]:
import numpy as np
arr = np.random.normal(5, 0.5, size=(3, 3, 3))

In [ ]:
arr = np.arange(1, 28).reshape(3,3,3)
print(arr)

[[[ 1  2  3]
  [ 4  5  6]
  [ 7  8  9]]

 [[10 11 12]
  [13 14 15]
  [16 17 18]]

 [[19 20 21]
  [22 23 24]
  [25 26 27]]]


In [ ]:
print([arr[x, :, :] for x in range(3)])
print([arr[:, y, :] for y in range(3)])                                          
print([arr[:, :, z] for z in range(3)])

[array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]]), array([[10, 11, 12],
       [13, 14, 15],
       [16, 17, 18]]), array([[19, 20, 21],
       [22, 23, 24],
       [25, 26, 27]])]
[array([[ 1,  2,  3],
       [10, 11, 12],
       [19, 20, 21]]), array([[ 4,  5,  6],
       [13, 14, 15],
       [22, 23, 24]]), array([[ 7,  8,  9],
       [16, 17, 18],
       [25, 26, 27]])]
[array([[ 1,  4,  7],
       [10, 13, 16],
       [19, 22, 25]]), array([[ 2,  5,  8],
       [11, 14, 17],
       [20, 23, 26]]), array([[ 3,  6,  9],
       [12, 15, 18],
       [21, 24, 27]])]


## 3

In [ ]:
mat = np.random.randint(10, size=(6,6))
mat

array([[0, 7, 3, 7, 4, 2],
       [3, 6, 9, 1, 3, 8],
       [6, 5, 4, 1, 2, 5],
       [0, 3, 5, 6, 9, 9],
       [9, 5, 5, 6, 7, 1],
       [0, 2, 1, 1, 9, 8]])

In [ ]:
import random
arr = np.array([random.random() for _ in range(10000)]) 